# Generated by Django 2.2.3 on 2019-07-03 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_evolution_key', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('method', models.CharField(max_length=250)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('description', models.TextField()),
                ('evolutions', models.ManyToManyField(to='api.Evolution')),
                ('types', models.ManyToManyField(to='api.Types')),
            ],
        ),
    ]
