# Generated by Django 2.2.3 on 2019-07-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolution',
            old_name='name',
            new_name='next_evolution_key',
        ),
    ]
