# Generated by Django 2.2.3 on 2019-07-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190703_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
