# Generated by Django 2.2.3 on 2019-07-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190703_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
